config/routes.rb
CharacterSheet::Application.routes.draw do
  resources :weapons
  resources :characters

  root :to => "characters#index"
  get 'characters' => 'character#index'

  

end

app/models/character.rb
class Character < ActiveRecord::Base
	has_many :weapons

	after_initialize do
		if self.new_record?
			self.strength = 3 + rand(6) + rand(6) + rand(6)
			self.dexterity = 3 + rand(6) + rand(6) + rand(6)
			self.constitution = 3 + rand(6) + rand(6) + rand(6)
			self.wisdom = 3 + rand(6) + rand(6) + rand(6)
			self.intelligence = 3 + rand(6) + rand(6) + rand(6)
			self.charisma = 3 + rand(6) + rand(6) + rand(6)

		end
	end
end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
	has_one :character
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render action: 'show', status: :created, location: @character }
      else
        format.html { render action: 'new' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:strength, :dexterity, :constitution, :wisdom, :intelligence, :charisma, :hit_points, :armor_class, :name, :level, :proficiencies_one, :proficiences_two, :proficiencies_three, :proficiencies_four, :proficiencies_five, :feat_one, :feat_two, :feat_three, :feat_four, :feat_five, :initiative, :speed)
    end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: [:show, :edit, :update, :destroy]

  # GET /weapons
  # GET /weapons.json
  def index
    @weapons = Weapon.all
  end

  # GET /weapons/1
  # GET /weapons/1.json
  def show
  end

  # GET /weapons/new
  def new
    @weapon = Weapon.new
  end

  # GET /weapons/1/edit
  def edit
  end

  # POST /weapons
  # POST /weapons.json
  def create
    @weapon = Weapon.new(weapon_params)
    @character = Character.all
    respond_to do |format|
      if @weapon.save
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @weapon }
      else
        format.html { render action: 'new' }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weapons/1
  # PATCH/PUT /weapons/1.json
  def update
    respond_to do |format|
      if @weapon.update(weapon_params)
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1
  # DELETE /weapons/1.json
  def destroy
    @weapon.destroy
    respond_to do |format|
      format.html { redirect_to weapons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weapon
      @weapon = Weapon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weapon_params
      params.require(:weapon).permit(:name, :dice_num, :dice_sides)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :strength %><br>
    <%= f.number_field :strength %>
  </div>
  <div class="field">
    <%= f.label :dexterity %><br>
    <%= f.number_field :dexterity %>
  </div>
  <div class="field">
    <%= f.label :constitution %><br>
    <%= f.number_field :constitution %>
  </div>
  <div class="field">
    <%= f.label :wisdom %><br>
    <%= f.number_field :wisdom %>
  </div>
  <div class="field">
    <%= f.label :intelligence %><br>
    <%= f.number_field :intelligence %>
  </div>
  <div class="field">
    <%= f.label :charisma %><br>
    <%= f.number_field :charisma %>
  </div>
  <div class="field">
    <%= f.label :hit_points %><br>
    <%= f.number_field :hit_points %>
  </div>
  <div class="field">
    <%= f.label :armor_class %><br>
    <%= f.number_field :armor_class %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :proficiencies_one %><br>
    <%= f.text_field :proficiencies_one %>
  </div>
  <div class="field">
    <%= f.label :proficiences_two %><br>
    <%= f.text_field :proficiences_two %>
  </div>
  <div class="field">
    <%= f.label :proficiencies_three %><br>
    <%= f.text_field :proficiencies_three %>
  </div>
  <div class="field">
    <%= f.label :proficiencies_four %><br>
    <%= f.text_field :proficiencies_four %>
  </div>
  <div class="field">
    <%= f.label :proficiencies_five %><br>
    <%= f.text_field :proficiencies_five %>
  </div>
  <div class="field">
    <%= f.label :feat_one %><br>
    <%= f.text_field :feat_one %>
  </div>
  <div class="field">
    <%= f.label :feat_two %><br>
    <%= f.text_field :feat_two %>
  </div>
  <div class="field">
    <%= f.label :feat_three %><br>
    <%= f.text_field :feat_three %>
  </div>
  <div class="field">
    <%= f.label :feat_four %><br>
    <%= f.text_field :feat_four %>
  </div>
  <div class="field">
    <%= f.label :feat_five %><br>
    <%= f.text_field :feat_five %>
  </div>
  <div class="field">
    <%= f.label :initiative %><br>
    <%= f.number_field :initiative %>
  </div>
  <div class="field">
    <%= f.label :speed %><br>
    <%= f.number_field :speed %>
  </div>
  <div class="field">
    <%= f.label :biography %><br>
    <%= f.text_area :biography %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>
<div class = "test"> hello </div>
<table>
  <thead>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <th>Name</th>
      <th>Level</th>
      <th></th>
      <th>Action</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td class = "name-text"><%= character.name %></td>
        <td class = "level-text"><%= character.level %> </td>
        <td class = "action-text"><%= link_to 'Show', character %></td>
        <td class = "action-text"><%= link_to 'Edit', edit_character_path(character) %></td>
        <td class = "action-text"><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>
<div class = "content-box">
  <center> <img src = "/ad&d-banner-dark.jpg"> </center>
  
  <div class = "name-box">
    <p class = "name-show-text">
      <strong>Name:</strong>
      <%= @character.name %>
    </p>
  </div>

  </br>
  </br>

  <div class = "hit-point-box">
      <strong>Hit points:</strong>
      <%= @character.hit_points %>
  </div>



  <div class = "stat-box">
    <div class = "stat-holder">
      <img class = "stat-icon" src="/stats/str.png" />
      <div class = "stat-show-text">
        <strong>Strength:</strong>
        <%= @character.strength %>
      </div>
    </div>

    <div class = "stat-holder">
      <img class = "stat-icon" src="/stats/dex.png" />
      <div class = "stat-show-text">
        <strong>Dexterity:</strong>
        <%= @character.dexterity %>
      </div>
    </div>

    <div class = "stat-holder">
      <img class = "stat-icon" src="/stats/con.png" />
      <div class = "stat-show-text">
        <strong>Constituion:</strong>
        <%= @character.constitution %>
      </div>
    </div>

    <div class = "stat-holder">
        <img class = "stat-icon" src="/stats/wis.png" />
        <div class = "stat-show-text">
          <strong>Wisdom:</strong>
          <%= @character.wisdom %>
        </div>
    </div>

    <div class = "stat-holder">
        <img class = "stat-icon" src="/stats/int.png" />
        <div class = "stat-show-text">
          <strong>Intelligence:</strong>
          <%= @character.intelligence %>
        </div>
    </div>

    <div class = "stat-holder">
        <img class = "stat-icon" src="/stats/cha.png" />
        <div class = "stat-show-text">
          <strong>Charisma:</strong>
          <%= @character.charisma %>
        </div>
    </div>
  </div>

  <div class = "level-box">
    <strong>Level:</strong>
    <%= @character.level %>
  </div>

  <p>
    <strong>Armor class:</strong>
    <%= @character.armor_class %>
  </p>

  

 
  <p>
    <strong>Proficiencies one:</strong>
    <%= @character.proficiencies_one %>
  </p>

  <p>
    <strong>Proficiences two:</strong>
    <%= @character.proficiences_two %>
  </p>

  <p>
    <strong>Proficiencies three:</strong>
    <%= @character.proficiencies_three %>
  </p>

  <p>
    <strong>Proficiencies four:</strong>
    <%= @character.proficiencies_four %>
  </p>

  <p>
    <strong>Proficiencies five:</strong>
    <%= @character.proficiencies_five %>
  </p>

  <p>
    <strong>Feat one:</strong>
    <%= @character.feat_one %>
  </p>

  <p>
    <strong>Feat two:</strong>
    <%= @character.feat_two %>
  </p>

  <p>
    <strong>Feat three:</strong>
    <%= @character.feat_three %>
  </p>

  <p>
    <strong>Feat four:</strong>
    <%= @character.feat_four %>
  </p>

  <p>
    <strong>Feat five:</strong>
    <%= @character.feat_five %>
  </p>

  <p>
    <strong>Initiative:</strong>
    <%= @character.initiative %>
  </p>

  <p>
    <strong>Speed:</strong>
    <%= @character.speed %>
  </p>

  <%= link_to 'Edit', edit_character_path(@character) %> |
  <%= link_to 'Back', characters_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharacterSheet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body class='<%= controller.controller_name %>' style = "background-color:black">

<%= yield %>

</body>
</html>

app/views/weapons/_form.html.erb
<%= form_for(@weapon) do |f| %>
  <% if @weapon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
      <% @weapon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dice_num %><br>
    <%= f.number_field :dice_num %>
  </div>
  <div class="field">
    <%= f.label :dice_sides %><br>
    <%= f.number_field :dice_sides %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weapons/edit.html.erb
<h1>Editing weapon</h1>

<%= render 'form' %>

<%= link_to 'Show', @weapon %> |
<%= link_to 'Back', weapons_path %>

app/views/weapons/index.html.erb
<h1>Listing weapons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dice num</th>
      <th>Dice sides</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @weapons.each do |weapon| %>
      <tr>
        <td><%= weapon.name %></td>
        <td><%= weapon.dice_num %></td>
        <td><%= weapon.dice_sides %></td>
        <td><%= link_to 'Show', weapon %></td>
        <td><%= link_to 'Edit', edit_weapon_path(weapon) %></td>
        <td><%= link_to 'Destroy', weapon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weapon', new_weapon_path %>

app/views/weapons/new.html.erb
<h1>New weapon</h1>

<%= render 'form' %>

<%= link_to 'Back', weapons_path %>

app/views/weapons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weapon.name %>
</p>

<p>
  <strong>Dice num:</strong>
  <%= @weapon.dice_num %>
</p>

<p>
  <strong>Dice sides:</strong>
  <%= @weapon.dice_sides %>
</p>

<%= link_to 'Edit', edit_weapon_path(@weapon) %> |
<%= link_to 'Back', weapons_path %>